export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const DEVICE_CHECK_OTP_SUCCESS = 'DEVICE_CHECK_OTP_SUCCESS';
export const DEVICE_CHECK_OTP_FAIL = 'DEVICE_CHECK_OTP_FAIL';

export const LOGIN_LOADNIG = 'LOGIN_LOADING';
export const MPIN_LOADING = 'MPIN_LOADING';
export const GET_ERROR = 'GET_ERROR';
export const MPIN_SUCCESS = 'MPIN_SUCCESS';
export const MPIN_FAIL = 'MPIN_FAIL';
export const FORGOT_PASS_OTP_SUCCESS = 'FORGOT_PASS_OTP_SUCCESS';
export const FORGOT_PASS_OTP_FAIL = 'FORGOT_PASS_OTP_FAIL';
export const VALIDATE_OTP_SUCCESS = ' VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAIL = 'VALIDATE_OTP_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGET_MPIN_SUCCESS = ' FORGET_MPIN_SUCCESS';
export const FORGET_MPIN_FAIL = ' FORGET_MPIN_FAIL';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAIL = 'RESEND_OTP_FAIL';

export const FORGET_MPIN_OTP_SUCCESS = 'FORGET_MPIN_OTP_SUCCESS';
export const FORGET_MPIN_OTP_FAIL = 'FORGET_MPIN_OTP_FAIL';
export const UPDATE_MPIN_SUCCESS = 'UPDATE_MPIN_SUCCEESS';
export const UPDATE_MPIN_FAIL = 'UPDATE_MPIN_FAIL';

export const CREATE_OTP_BENEFICIARY_SUCCESS = 'CREATE_OTP_BENEFICIARY_SUCCESS';
export const CREATE_OTP_BENEFICIARY_FAIL = 'CREATE_OTP_BENEFICIARY_FAIL';
export const RESEND_OTP_BENEFICIARY_FAIL = 'RESEND_OTP_BENEFICIARY_FAIL';
export const RESEND_OTP_BENEFICIARY_SUCCESS = 'RESEND_OTP_BENEFICIARY_SUCCESS';

export const ADD_BENEFICIARY_SUCCESS = 'ADD_BENEFICIARY_SUCCESS';
export const ADD_BENEFICIARY_FAIL = ' ADD_BENEFICIARY_FAIL';

export const CATACH_ERROR = 'CATACH_ERROR';
export const GET_BENEFICIARY_SUCCESS = 'GET_BENEFICIARY_SUCCESS';
export const GET_BENEFICIARY_FAIL = 'GET_BENEFICIARY_FAIL';
export const REMOVE_BENEFICIARY_SUCCESS = 'REMOVE_BENEFICIARY_SUCCESS';
export const REMOVE_BENEFICIARY_FAIL = 'REMOVE_BENEFICIARY_FAIL';

export const UPDATE_BENEFICIARY_FAIL = 'UPDATE_BENEFICIARY_FAIL';
export const UPDATE_BENEFICIARY_SUCCESS = 'UPDATE_BENEFICIARY_SUCCESS';
export const DEVICEID_OTP = ' DEVICEID_OTP';
export const GET_MEMBER_DT_FAIL = 'GET_MEMBER_DT_FAIL';
export const GET_MEMBER_DT_SUCCESS = 'GET_MEMBER_DT_SUCCESS';
export const GET_RAZORPAY_DETAILS_SUCCESS = 'GET_RAZORPAY_DETAILS_SUCCESS';
export const GET_RAZORPAY_DETAILS_FAIL = ' GET_RAZORPAY_DETAILS_FAIL';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAIL = 'GET_CARD_FAIL';

export const GET_ACTIVE_METHOD = 'GET_ACTIVE_METHOD';

export const GET_BENECIARY_ACCOUNT = 'GET_BENEFICIARY_ACCOUNT';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const CREATE_MEMBAR_TOKEN_SUCCESS = 'CREATE_MEMBAR_TOKEN_SUCCESS';
export const CREATE_MEMBAR_TOKEN_FAIL = 'CREATE_MEMBAR_TOKEN_FAIL';
