export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const DEVICE_CHECK_OTP_SUCCESS = 'DEVICE_CHECK_OTP_SUCCESS';
export const DEVICE_CHECK_OTP_FAIL = 'DEVICE_CHECK_OTP_FAIL';

export const LOGIN_LOADNIG = 'LOGIN_LOADING';
export const MPIN_LOADING = 'MPIN_LOADING';
export const GET_ERROR = 'GET_ERROR';
export const MPIN_SUCCESS = 'MPIN_SUCCESS';
export const MPIN_FAIL = 'MPIN_FAIL';
export const FORGOT_PASS_OTP_SUCCESS = 'FORGOT_PASS_OTP_SUCCESS';
export const FORGOT_PASS_OTP_FAIL = 'FORGOT_PASS_OTP_FAIL';
export const VALIDATE_OTP_SUCCESS = ' VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAIL = 'VALIDATE_OTP_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGET_MPIN_SUCCESS = ' FORGET_MPIN_SUCCESS';
export const FORGET_MPIN_FAIL = ' FORGET_MPIN_FAIL';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAIL = 'RESEND_OTP_FAIL';

export const FORGET_MPIN_OTP_SUCCESS = 'FORGET_MPIN_OTP_SUCCESS';
export const FORGET_MPIN_OTP_FAIL = 'FORGET_MPIN_OTP_FAIL';
export const UPDATE_MPIN_SUCCESS = 'UPDATE_MPIN_SUCCEESS';
export const UPDATE_MPIN_FAIL = 'UPDATE_MPIN_FAIL';

export const CREATE_OTP_BENEFICIARY_SUCCESS = 'CREATE_OTP_BENEFICIARY_SUCCESS';
export const CREATE_OTP_BENEFICIARY_FAIL = 'CREATE_OTP_BENEFICIARY_FAIL';
export const RESEND_OTP_BENEFICIARY_FAIL = 'RESEND_OTP_BENEFICIARY_FAIL';
export const RESEND_OTP_BENEFICIARY_SUCCESS = 'RESEND_OTP_BENEFICIARY_SUCCESS';

export const ADD_BENEFICIARY_SUCCESS = 'ADD_BENEFICIARY_SUCCESS';
export const ADD_BENEFICIARY_FAIL = ' ADD_BENEFICIARY_FAIL';

export const CATACH_ERROR = 'CATACH_ERROR';
export const GET_BENEFICIARY_SUCCESS = 'GET_BENEFICIARY_SUCCESS';
export const GET_BENEFICIARY_FAIL = 'GET_BENEFICIARY_FAIL';
export const REMOVE_BENEFICIARY_SUCCESS = 'REMOVE_BENEFICIARY_SUCCESS';
export const REMOVE_BENEFICIARY_FAIL = 'REMOVE_BENEFICIARY_FAIL';

export const UPDATE_BENEFICIARY_FAIL = 'UPDATE_BENEFICIARY_FAIL';
export const UPDATE_BENEFICIARY_SUCCESS = 'UPDATE_BENEFICIARY_SUCCESS';
export const DEVICEID_OTP = ' DEVICEID_OTP';
export const GET_MEMBER_DT_FAIL = 'GET_MEMBER_DT_FAIL';
export const GET_MEMBER_DT_SUCCESS = 'GET_MEMBER_DT_SUCCESS';
export const GET_RAZORPAY_DETAILS_SUCCESS = 'GET_RAZORPAY_DETAILS_SUCCESS';
export const GET_RAZORPAY_DETAILS_FAIL = ' GET_RAZORPAY_DETAILS_FAIL';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAIL = 'GET_CARD_FAIL';

export const GET_ACTIVE_METHOD = 'GET_ACTIVE_METHOD';

export const GET_BENECIARY_ACCOUNT = 'GET_BENEFICIARY_ACCOUNT';

export const SIGNUP_USER_LOADING = 'SIGNUP_USER_LOADING';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const CREATE_MEMBAR_TOKEN_SUCCESS = 'CREATE_MEMBAR_TOKEN_SUCCESS';
export const CREATE_MEMBAR_TOKEN_FAIL = 'CREATE_MEMBAR_TOKEN_FAIL';
export const SIGNUP_CHECK_OTP_SUCCESS = 'SIGNUP__CHECK_OTP_SUCCESS';
export const SIGNUP__CHECK_OTP_FAIL = 'SIGNUP_CHECK_OTP_FAIL';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_PAYOUT_STATUS_SUCCESS = 'GET_PAYOUT_STATUS_SUCCESS';
export const CREATE_OTP_OUTSIDE_SUCCESS = 'CREATE_OTP_OUTSIDE_SUCCESS';
export const CREATE_OTP_OUTSIDE_FAIL = 'CREATE_OTP_OUTSIDE_FAIL';
export const TRANSACTION_WITHINCOOP_SUCCESS = 'TRANSACTION_WITHINCOOP_SUCCESS';
export const TRANSACTION_WITHINCOOP_FAIL = 'TRANSACTION_WITHINCOOP_FAIL';
export const CREATE_OTP_BUSINESS_SUCCESS = 'CREATE_OTP_BUSINESS_SUCCESS';
export const TRANSACTION_WITHINCOOP_SPARK_SUCCESS =
  'TRANSACTION_WITHINCOOP_SPARK_SUCCESS';
export const ISFIN_BUS_RD_SUCCESS = 'ISFIN_BUS_RD_SUCCESS';
export const ISFIN_BUS_RD_FAIL = 'ISFIN_BUS_RD_FAIL';

export const GET_PROFILE_SUCCUESS = 'GET_PROFILE_SUCCUESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PREPAID_BILLER_SUCCESS = 'GET_PREPAID_BILLER_SUCCESS';
export const GET_PREPAID_BILLER_FAIL = 'GET_PREPAID_BILLER_FAIL';

export const CREATE_OTP_EDITPROFILE_SUCCESS = 'CREATE_OTP_EDITPROFILE_SUCCESS';
export const CREATE_OTP_EDITPROFILE_FAIL = 'CREATE_OTP_EDITPROFILE_FAIL';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS';
export const GET_TRANSACTION_FAIL = 'GET_TRANSACTION_FAIL';

export const STATEMENT_DATE_SUCCESS = 'STATEMENT_DATE_SUCCESS';
export const STATEMENT_DATE_FAIL = 'STATEMENT_DATE_FAIL';

export const CATAGORY_RECENT_TXNS_SUCCESS = 'CATAGORY_RECENT_TXNS_SUCCESS';

export const CATAGORY_RECENT_TXNS_FAIL = 'CATAGORY_RECENT_TXNS_FAIL';
export const GET_CUSTMER_DETAILS_SUCCESS = 'GET_CUSTMER_DETAILS_SUCCESS';
export const GET_CUSTMER_DETAILS_FAIL = 'GET_CUSTMER_DETAILS_SUCCESS';

export const SEND_BILL_FETCH_SUCCESS = 'SEND_BILL_FETCH_SUCCESS';
export const SEND_BILL_FETCH_FAIL = 'SEND_BILL_FETCH_FAIL';

export const CONENIENCE_FEES_SUCCESS = 'CONENIENCE_FEES_SUCCESS';

export const CONENIENCE_FEES_FAIL = 'CONENIENCE_FEES_FAIL';

export const GET_PROMO_CODE_SUCCESS = 'GET_PROMO_CODE_SUCCESS';
export const GET_PROMO_CODE_FAIL = 'GET_PROMO_CODE_FAIL';

export const OTP_BILL_PAYMENT_SUCCESS = 'OTP_BILL_PAYMENT_SUCCESS';

export const OTP_BILL_PAYMENT_FAIL = 'OTP_BILL_PAYMENT_FAIL';
export const GET_ACTIVE_FD_SUCCESS = 'GET_ACTIVE_FD_SUCCESS';
export const GET_ACTIVE_FD_FAIL = 'GET_ACTIVE_FD_FAIL';

export const INSERT_CUSTMER_DETAILS_SUCCESS = 'INSERT_CUSTMER_DETAILS_SUCCESS';

export const INSERT_CUSTMER_DETAILS_FAIL = 'INSERT_CUSTMER_DETAILS_FAIL';

export const GET_ACTIVE_REFERRAL_CODE_SUCCESS =
  'GET_ACTIVE_REFERRAL_CODE_SUCCESS';

export const GET_ACTIVE_REFERRAL_CODE_FAIL = 'GET_ACTIVE_REFERRAL_CODE_FAIL';
export const CREATE_OTP_FD_SUCCESS = 'CREATE_OTP_FD_SUCCESS';
export const CREATE_OTP_FD_FAIL = 'CREATE_OTP_FD_FAIL';
export const RESEND_OTP_FD_SUCESS = 'RESEND_OTP_FD_SUCESS';
export const RESEND_OTP_FD_FAIL = 'RESEND_OTP_FD_FAIL';
 export const TRANSACTION_WITHINCOOP_SPARK_FAIL="TRANSACTION_WITHINCOOP_SPARK_FAIL"
export const CREARE_FD_SUCCESS = 'CREARE_FD_SUCCESS';
export const CREARE_FD_FAIL = 'CREARE_FD_FAIL';
export const VIEW_FD_SUCCESS = 'VIEW_FD_SUCCESS';
export const VIEW_FD_FAIL = 'VIEW_FD_FAIL';
export const STATEMENT_FD_SUCCESS = 'STATEMENT_FD_SUCCESS';
export const STATEMENT_FD_FAIL = 'STATEMENT_FD_FAIL';
export const SEND_FD_STATEMENT_SUCCESS = 'SEND_FD_STATEMENT_SUCCESS';
export const SEND_FD_STATEMENT_FAIL = 'SEND_FD_STATEMENT_FAIl';

export const GET_CANCEL_FD_SUCCESS = 'GET_CANCEL_FD_SUCCESS';
export const GET_CANCEL_FD_FAIL = 'GET_CANCEL_FD_FAIL';
export const CREATE_OTPFD_CANCEL_SUCCESS = 'CREATE_OTPFD_CANCEL_SUCCESS';

export const CREATE_OTPFD_CANCEL_FAIL = 'CREATE_OTPFD_CANCEL_FAIL';

export const GET_FD_CHART_SUCCESS = 'GET_FD_CHART_SUCCESS';
export const GET_FD_CHART_FAIL = 'GET_FD_CHART_FAIL';

export const CREATE_OTP_RD_SUCCESS = 'CREATE_OTP_RD_SUCCESS';
export const CREATE_OTP_RD_FAIL = 'CREATE_OTP_RD_FAIL';

export const RESEND_OTP_RD_SUCCESS = 'RESEND_OTP_RD_SUCCESS';
export const RESEND_OTP_RD_FAIL = 'RESEND_OTP_RD_FAIL';
export const CREATE_RD_SUCCESS = 'CREATE_RD_SUCCESS';
export const CREATE_RD_FAIL = 'CREATE_RD_FAIL';
export const ACTIVE_RD_SUCCESS = 'ACTIVE_RD_SUCCESS';
export const ACTIVE_RD_FAIL = 'ACTIVE_RD_FAIL';
 export const SESSION_MISSING="SESSION_MISSING"


 
 export const CREATE_SCHEDULE_SUCCESS="CREATE_SCHEDULE_SUCCESS";
 export const CREATE_SCHEDULE_FAIL="CREATE_SCHEDULE_FAIL"
   export const CREATE_OTP_SCHEDULE_SUCCESS="CREATE_OTP_SCHEDULE_SUCCESS";
   export const CREATE_OTP_SCHEDULE_FAIL="CREATE_OTP_SCHEDULE_FAIL"

    export  const RESEND_OTP_SCHEDULE_SUCCESS="RESEND_OTP_SCHEDULE_SUCCESS";
    export  const RESEND_OTP_SCHEDULE_FAIL="RESEND_OTP_SCHEDULE_FAIL";
     export const ACCOUNT_BALANCE_RAZORPAY_SUCCESS="ACCOUNT_BALANCE_RAZORPAY_SUCCESS"
    
     export const  ACCOUNT_BALANCE_RAZORPAY_FAIL= "ACCOUNT_BALANCE_RAZORPAY_FAIL"